"""Numerical report generated from recomputed results; interpretation kept explicit."""
from pathlib import Path
import json
import numpy as np
from analyze_pilot import compute
from shadow_readers import calculate
from analyze_air_pathway51 import compute as pathway
H=Path(__file__).resolve().parent
def read(n):return json.loads((H/n).read_text())
def f(x):return f'{x:.7g}'

def main():
 r,_=compute(H);shadow,_=calculate(H);path=pathway(H);queue=read('QUEUE_RESULT.json');local=read('LOCAL_RESULTS.json');anatomy=read('ANATOMICAL_PROJECTION.json');old=read('READERS.json');clipping=read('CLIPPING_SUPPLEMENT.json');body=read('BODY_SUPPLEMENT.json');peer=read('aporte_motor/revision_final51/RESULTADO.json')
 air_signal=all(r['air'][str(o)]['both_material'] and all(v['relay_response_present'] for v in path['observations'][str(o)].values()) for o in [0,1])
 classification='PROMETEDOR_NO_CONFIRMADO' if air_signal or r['conductance']['promising_screen'] else 'DESCARTADO'
 g=r['conductance'];verdict=dict(classification=classification,scope='Short transfer screen; not navigation, autonomous initiation, learning or biological equivalence',air_screen_material_with_pathway=air_signal,conductance_screen_promising=g['promising_screen'],stage4_pass=r['stage4_pass'],stage5_pass=r['stage5_pass'],physical_relative_air_units_valid=False,unit_correction_CNS_qualified=False,full_prototypes=2,scientific_arms=len(queue['arms']),attempted_neural_ms=queue['attempted_ms'],stop_reason='Bounded comparison milestone complete; no further tuning or neural interaction in this campaign')
 (H/'VERDICT.json').write_text(json.dumps(verdict,indent=2)+'\n')
 lines=['# Campaña 51: comparación ejecutada de alternativas','',f'**Etapas 4 y 5 abiertas. Clasificación: {classification}, restringida a transferencia neuronal.** Se completaron diez condiciones de 90 ms y 16 ms de cualificación. Ningún brazo aplicó el mando de giro al cuerpo; no hubo perturbación mecánica reservada. Esta campaña no puede acreditar navegación ni recuperación.','',
 'La propuesta anterior contenía doce opciones de cuatro autores, agrupadas aquí en diez familias por sus coincidencias. Todas recibieron una prueba discriminante local o un diagnóstico de identificabilidad; sólo aire y ley neuronal se integraron en el organismo completo. El trasplante PN operativo y la cinta propioceptiva completa siguen pendientes. No se presentan como experimentos realizados.','',
 '**Fallo de integración descubierto en revisión final:** faltó convertir ×10 la velocidad corporal de cm/s a mm/s antes del receptor de aire. Afecta también G/I con campo cero, porque el cuerpo se mueve. Conservamos los resultados como ejecutados; la versión física corregida no fue reejecutada. La copia correctiva y el test CPU de movimiento conjunto aire/cuerpo están en AIR_UNITS_REPAIR.json y AIR_BODY_UNITS_TEST.json. El PASS de las comprobaciones originales no cubría este contrato de unidades. No promover ninguna variante a lazo físico sobre esos PASS.','', '## Resultado del organismo completo','',
 '| Condición | Media DNb05 izquierda−derecha | Giro calculado, sin aplicar (°/s) | Máximo target DNg100 | Mando de avance bruto (mm/s) |',
 '|---|---:|---:|---:|---:|']
 for arm,a in r['arms'].items():lines.append(f"| {arm} | {f(a['mean_DNb_direction'])} | {f(a['mean_yaw_deg_s'])} | {f(a['DNg_target_max'])} | {f(a['mean_forward'])} |")
 lines+=['','Medias en la ventana prospectiva 51–90 ms. `q` de los registros es salida normalizada float64 de `hybrid.release()`, distinta de tasas publicadas float32. Para las DN genéricas observadas coincide con su estado; la salida visual transforma el estado interno. El propietario G/I toma su q0 del estado interno completo, comprobado contra el checkpoint de 48.','',
 '| Contraste de aire: mitad izquierda−derecha | Sin olor | Con olor | Mínimo absoluto previo |','|---|---:|---:|---:|',
 f"| DNb05 q L−R | {f(r['air']['0']['half_L_minus_R_DNb_q'])} | {f(r['air']['1']['half_L_minus_R_DNb_q'])} | 0,000016 |",
 f"| Giro calculado (°/s) | {f(r['air']['0']['half_L_minus_R_yaw_deg_s'])} | {f(r['air']['1']['half_L_minus_R_yaw_deg_s'])} | 0,02 |",'',
 f"La diferencia de esos contrastes al añadir olor es {f(r['odor_modulation_of_air_direction']['q'])} en q y {f(r['odor_modulation_of_air_direction']['yaw_deg_s'])} °/s. El criterio de materialidad corresponde a cada contraste primario; la interacción con olor se informa sin inventar un criterio retrospectivo. Los relés seleccionados antes de ejecutar responden en ambos sentidos del campo. Los giros medios conservan el mismo signo; además, el contraste instantáneo cambia de signo dentro de la propia ventana51–90ms. Su media no acredita un código direccional estable ni una ley bidireccional de orientación correcta.",
 '',f"**Confusión pendiente entre patrón y entrada total:** el campo izquierdo activa {path['observations']['0']['L']['nonzero_JO_at51']} receptores y suma {f(path['observations']['0']['L']['mean_total_JO_drive'])} unidades; el derecho activa {path['observations']['0']['R']['nonzero_JO_at51']} y suma {f(path['observations']['0']['R']['mean_total_JO_drive'])}. Se conserva la misma ley por receptor y la desigualdad anatómica, sin ajustar por el resultado. Este experimento muestra dependencia respecto al campo suministrado, pero no selectividad por dirección a intensidad total igualada.",
 '',f"**Ley neuronal G frente a corriente emparejada I:** la diferencia entre respuestas olor−sin olor es {f(g['G_minus_I_odor_effect_q'])} en DNb05 q L−R y {f(g['G_minus_I_odor_effect_yaw_deg_s'])} °/s. Criterio conjunto material: {g['both_material']}; exclusión por saturación: {g['saturation_excluded']}; supervivencia de esta criba: {g['promising_screen']}. Este resultado se refiere a la variante normalizada y acotada evaluada, no a todas las conductancias posibles.",
 '', '![Comparación de las diez condiciones](COMPARACION.png)', '', f"El target de DNg100 se abre bajo G e I incluso sin olor. El cuerpo cambia: desplazamiento G={f(np.linalg.norm(body['arms']['G_odor0']['recorded_step1_to90_displacement_mm']))} mm, I={f(np.linalg.norm(body['arms']['I_odor0']['recorded_step1_to90_displacement_mm']))} mm, padre={f(np.linalg.norm(body['arms']['air0_odor0']['recorded_step1_to90_displacement_mm']))} mm entre las muestras1 y90. El mando de avance de la tabla no es esa velocidad medida. BODY_SUPPLEMENT.json conserva posiciones, velocidades y diferencias; no acredita locomoción orientada.",'', '## Operaciones y límites de la prueba', '',
 'Aire: campo mundial fijo ±100 mm/s en el eje lateral inicial; el receptor recibe aire relativo al cuerpo, no ubicación del olor ni rumbo correcto. Añade drive sólo a 335 JO-C/E y mantiene la recurrencia. La saturación utiliza s=max(proyección firmada,0), siempre no negativa. Los ejes a 45°, 80 unidades y semisaturación 100 mm/s son supuestos de ingeniería. Campo cero conserva la contribución del movimiento relativo del cuerpo. Aire sensorial y torque físico son intervenciones diferentes.', '',
 'G/I: X=E+drive positivo, Y=I+theta+drive negativo en magnitud; S=X0+Y0 y q0 se congelan al adoptar el modelo. EL=2q0−X0/S es un sesgo compensatorio, no un potencial fisiológico medido. Ambas variantes igualan el valor basal y relajación inicial; I conserva el shunt basal. G cambia la relajación con E+I y ambas recortan target a [0,1]. Se sustituyó sólo la ley BASE genérica, preservando posteriores reemplazos especializados. Un contraste incluye la dinámica recurrente y cualquier realimentación cuerpo→aire que cambie, no sólo una fila local.', '',
 '| Variante | Filas BASE que alguna vez salen por debajo de 0 | Por encima de 1 | Fracción de nuevas saturadas en población elegible |', '|---|---:|---:|---:|']
 for arm,c in r['clipping'].items():lines.append(f"| {arm} | {c['base_rows_raw_below0']} | {c['base_rows_raw_above1']} | {f(c['new_saturation_eligible_fraction'])} |")
 lines+=['', 'Los extremos son anteriores a los reemplazos especializados; no equivalen a fracción de estados finales recortados. CLIPPING_SUPPLEMENT.json reconstruye además la frecuencia de recorte de todas las evaluaciones DNg100 registradas, incluidas pruebas del integrador. No se guardó esa frecuencia por evaluación para todas las demás filas. Por ello una diferencia no se atribuye automáticamente a un shunt puro.', '',
 '## Comparación de las diez familias', '',
 '| Familia y proponente | Prueba ejecutada | Resultado y alcance |', '|---|---|---|',
 '| Cinco pares DN (ASTRA; instrumentación Motor_V2) | 30 publicaciones por brazo de 48; cinco lectores en las diez continuaciones de 51 | Mediana y media sin pesos ajustados; resultados nuevos abajo. No se aplicó otro decoder al cuerpo. |',
 '| Oponente DNb05/DNb06 (autor) | Mismos registros y signos fijados | En 48 DNb06 no añade señal; la combinación equivale al aporte DNb05 escalado. No es rescate por sí misma. |',
 '| Acciones DNa02/DNg13 (Motor) | Mismos registros, sin buscar otras DN tras ver el resultado | En 48 ambos canales son silenciosos en precisión publicada; en 51 se informa la lectura float64 sin redondear residuos a actividad material. |',
 f"| Proyección DN→premotor→MN (Motor_V2) | Anatomía canónica: conexiones directas y dos saltos, todos los intermedios; 708 MN con somaSide | Aporte extra frente a DNb05: {f(anatomy['max_extra_ensemble_signal_vs_DNb05'])} en la criba48. Conteos y lado somático no son una ley muscular ni garantizan signo de giro. |",
 '| Trasplante PN recíproco (Motor_V2) | Cirugía CPU de 1372 posiciones q/filtro de 686 ALPN y propietario fino completo de 37 arrays y escalares | No-op y reversión exactos; cuatro corrupciones downstream rechazadas. Falta cualificar eventos/cachés y evolución CNS viva. |',
 f"| Predictor/JVP (ASTRA; operación local Motor_V2) | Contrafactual de transmisiones ALPN observadas sobre seis filas DN reales | Errores relativos lineal vs finito {f(local['PN_JVP']['sham']['relative_error'])} y {f(local['PN_JVP']['profile']['relative_error'])}. DNb05 responde con signo local coherente; DNg100 sigue cerrado en este contrafactual. No es un propagador de toda la red ni steering validado. |",
 '| Conductancias (Motor y autor, especificación ASTRA) | Conversión visual local; comparación basal G/I corregida; cuatro condiciones completas | La conversión directa produce gran deriva basal, no rescate olfativo. El ensayo emparejado se interpreta con su resultado y clipping explícitos. |',
 f"| Regulación intrínseca (autor) | Seis filas a entrada registrada constante, 50 ms; control de sesgo medio | Diferencia máxima {f(max(v['dynamic_minus_static_max'] for v in local['intrinsic'].values()))}; no rescata DNg100. Negativo para esta parametrización local, no para toda homeostasis recurrente. |",
 '| Aire antenal (Motor) | Anatomía, 18 controles CPU y seis condiciones completas | Respuesta en JO, relés y DNb05; contraste material sin prueba de giro correcto ni especificidad olfativa. |',
 '| Contexto propioceptivo (ASTRA) | Contraejemplo geométrico usando el receptor actual y revisión del donante local previo | Las medidas2D de tres patas de Fujiwara no identifican seis ángulos3D: mismas proyecciones/longitudes, ángulos90° y144,7356°. Existe un donante de cinemática reconstruida por IK; el replay previo335ms frente a postura retenida fue negativo para DNa02. No repetirlo como novedad. |', '',
 '## Lectores alternativos sobre las nuevas continuaciones', '', '| Lector en sombra | Contraste aire sin olor | Contraste aire con olor | Interacción G−I con olor |', '|---|---:|---:|---:|']
 for name,s in shadow['readers'].items():lines.append(f"| {name} | {f(s['air_L_minus_R_half']['0'])} | {f(s['air_L_minus_R_half']['1'])} | {f(s['G_minus_I_odor_interaction'])} |")
 lines+=['', 'G/I también reactivan basalmente DNa02/DNg13 y la mediana: no permanecerían silenciosos bajo cualquier ley. Casi el mismo cambio aparece sin olor, por lo que no se interpreta como rescate selectivo. Unidades normalizadas de cada lector, no °/s; la proyección anatómica tiene una escala diferente. Pares, signos y pesos anatómicos se fijaron antes de estos arrays. Baseline propio de los primeros10ms; no entrenamiento ni selección de ganador por navegación.', '',
 '## Verificación, recursos y revisión', '',
 f"CPU instrumentada del piloto y cualificación: {queue['CPU_s']:.2f} s; pared de la cola científica: {queue['queue_wall_s']:.2f} s; tiempo desde congelación: {queue['pilot_elapsed_s']:.2f} s. Interacción consumida: {queue['attempted_ms']} ms de {read('PILOT_PLAN.json')['budgets']['neural_ms_total']} autorizados para esta ronda. Cero reintentos de brazos científicos. Las cribas locales tienen costes por ejecutable; importaciones, lecturas y reparaciones auxiliares no se presentan como CPU total de sesión medida.", '',
 f"La revisión final de Motor C++/CUDA recalculó por separado los diez contrastes y coincidió con estas cifras; detectó además el fallo físico de unidades. Con la trayectoria observada fija, corregir la velocidad cambia la entrada máxima por receptor G_olor={f(peer['arms']['G_odor1']['velocity_units_corrected_JO_max_abs_change'])}, I_olor={f(peer['arms']['I_odor1']['velocity_units_corrected_JO_max_abs_change'])}; cambios máximos de suma instantánea {f(peer['arms']['G_odor1']['velocity_units_corrected_JO_max_total_change'])} y {f(peer['arms']['I_odor1']['velocity_units_corrected_JO_max_total_change'])}. No son cotas del CNS corregido. En aire sin avance, el cambio por receptor es mucho menor. El test CPU correctivo da movimiento conjunto nulo y expone el fallo antiguo con velocidades conocidas; ejecución CNS corregida pendiente.",'', 'La cualificación16ms compara las33 observaciones del padre con49, q0 interno con48, adopción común G/I y ecuaciones CPU/CUDA en3232 evaluaciones-célula DNg por variante. La evidencia completa se recalcula desde arrays y contrato, también bajo Python -O, con pruebas de corrupción y hashes. Véase REPRODUCIR.md. Preservamos fallos auxiliares de metadatos PN, selección de lado somático, orden de suma y confusión estado/salida del verificador portable; no cambiaron el algoritmo científico ni tolerancias para cambiar una conclusión.', '',
 'Una preparación inicial común, un campo por lado y una ventana de90ms: los puntos temporales no son semillas independientes. No hay intervalos poblacionales ni cohorte confirmatoria reservada. El nuevo checkpoint51 conserva su propietario y esquema propio; su reanudación GPU portable no está cualificada.', '',
 'ChatGPT ASTRA_V2 revisó normalización, control basal y límites de clipping; ChatGPT_Motor_V2 distinguió signo local matemático de steering y delimitó el trasplante; Motor C++/CUDA aportó anatomía, receptor de aire y la prueba propioceptiva. Se conservan textos y fuentes. Sus recomendaciones no sustituyen medidas; no se atribuye PRO verificado ni revisión ciega. La revisión final local independiente, si está presente en aporte_motor, identifica qué arrays recalculó.', '',
 '## Decisión y próximas alternativas', '',
 'A. Primero cualificar y repetir la corrección de unidades en otra ronda acotada; conservar provisionalmente el receptor de aire y comprobar dirección frente a entrada total emparejada, permutación y replay. Sólo después probar su utilidad física con el cuerpo actual y lector congelado, separando orientación asistida de iniciación autónoma. No ajustar el signo ni recentrar el mando con los resultados de estas diez condiciones.', '',
 'B. Completar la intervención recíproca PN con carga viva, estado de eventos y control no-op antes de gastar una nueva comparación CNS. El JVP local aporta una predicción comprobable de transferencia hacia DNb05; aún no localiza por sí solo toda la limitación posterior.', '',
 'C. Si se prueba contexto locomotor, reutilizar el donante IK local como reconstrucción declarada y contrastar coordinación temporal con marginales sensoriales iguales. No completar grados de libertad desconocidos presentándolos como medición ni repetir el negativo previo de postura retenida. Las patas/músculos siguen posteriores; no se integra una marcha completa para ocultar la falta de mando.', '',
 'Los dos ChatGPT coinciden en priorizar la interfaz aérea condicionada a reparación y control de intensidad, y reducir la prioridad de G como mejora selectiva del olor. Motor_V2 precisa que el emparejamiento debe comprobarse en la entrada JO realmente consumida, no sólo en número de receptores o campo impuesto. ASTRA distingue excitabilidad basal de transferencia informativa. No se adopta literalmente su referencia a filas clippeadas: los conteos registrados son de target BASE antes de reemplazos especializados.','', 'Cada ruta necesita otro contrato y presupuesto antes de ejecutarse; se conserva el límite de dos prototipos completos por ronda. Este cierre termina una comparación acotada, no declara imposibilidad del proyecto ni promete que las etapas sean alcanzables con la variante actual. Un efecto neuronal útil no sustituye la conducta online y el control por replay de etapa4 ni la recuperación mecánica reservada de etapa5.', '',
 'Fuentes y procedencia: PILOT_PLAN.json, PILOT_SOURCES.json, PARENT_DIFF.patch, datos por condición y suplementos. La motivación cualitativa de JO-C/E está en [Suver2019](https://pmc.ncbi.nlm.nih.gov/articles/PMC6533146/); la limitación de observables propioceptivos usa la documentación del [depósito Fujiwara](https://zenodo.org/records/6365304). Ninguna fuente calibra automáticamente nuestros ejes, amplitudes, pesos ni receptores.', '']
 (H/'RESULTADOS.md').write_text('\n'.join(lines))
 print(json.dumps(verdict))

if __name__=='__main__':main()
